name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: arindamvm/githubvm
      run: docker run --privileged -p 6080:6080 -p 2221:2222 -v $PWD/vmdata:/data arindamvm/githubvm
